name: Fetch Shopify Schemas (via graphql-codegen)

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies & fix peer deps
        run: |
          ls
          npm install --legacy-peer-deps
          npm dedupe


      - name: Fetch schemas via graphql-codegen introspection
        env:
          SHOPIFY_STOREFRONT_TOKEN: ${{ secrets.STOREFRONT_API_KEY }}
          SHOPIFY_ADMIN_TOKEN: ${{ secrets.ADMIN_API_KEY }}
        run: graphql-codegen --config codegen-schema.yaml

      - name: Commit & push schemas
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./storefront/storefront-schema.json ./admin/admin-schema.json
          git commit -m "chore: fetch Shopify schemas [skip ci]" || echo "no changes"
          git push
